### PR TITLE
add transition to buttons

### PR DESCRIPTION
**Pull request by imdevarsh**
This is half of #13

### CODE REVIEW

**Comment by imdevarsh** [comment]
Also fixes the back button.

**Comment by jdev082** [comment]
I don't approve of your "add back lock file" commit
pnpm generates it automatically off an npm lock  json file so why?

**Comment by imdevarsh** [comment]
You have a `package-lock.json`?

**Comment by imdevarsh** [comment]
https://docs.npmjs.com/cli/v6/configuring-npm/package-locks
This is an explanation for lockfiles

**Comment by imdevarsh** [comment]
> It is highly recommended you commit the generated package lock to source control: this will allow anyone else on your team, your deployments, your CI/continuous integration, and anyone else who runs (p)npm install in your package source to get the exact same dependency tree that you were developing on. Additionally, the diffs from these changes are human-readable and will inform you of any changes (p)npm has made to your node_modules, so you can notice if any transitive dependencies were updated, hoisted, etc.

Added `(p)` brackets since it applies to `pnpm` too

**Comment by imdevarsh** [comment]
I'll revert it if you want.

**Comment by jdev082** [comment]
I already have an npm compatible package lock, one needed for pnpm is not needed.

**Comment by imdevarsh** [comment]
I don't see it...
Anyways, @JaydenDev merge

**Comment by imdevarsh** [comment]
LOL - it's adding the lockfile back
Should I change the action to use `npm` since you hate `pnpm`?

**Comment by jdev082** [comment]
add it back to the git ignore.

**Comment by imdevarsh** [comment]
OK.

**Comment by imdevarsh** [comment]
You'll have to have a `package-lock.json` for it to work.

**Comment by jdev082** [comment]
> You'll have to have a `package-lock.json` for it to work.

no pnpm lock goes in git ignore that one doesnt'

**Comment by imdevarsh** [comment]
Yes, but you didn't generate a package lock. Generate one after merging this PR. I'll continue to use PNPM when I do my work, but not commit the file.

**Comment by jdev082** [comment]
> Yes, but you didn't generate a package lock. Generate one after merging this PR. I'll continue to use PNPM when I do my work, but not commit the file.

If you encounter any issues I won't be offering support, since you are using pnpm. I will just direct you to use NPM.

**Comment by imdevarsh** [comment]
I'll debug it myself. And anyways, that's the whole reason the action is there. For those who don't/can't use NPM.

**Comment by jdev082** [comment]
@webdev03 you failed to give me a chance to merge this.

**Comment by imdevarsh** [comment]
I wanted to stop the argument.

**Pull request closed without merging**
