### PR TITLE
Fix icon alignment

### PR DESCRIPTION
**Pull request by hello-smile6**
Closes #6

### CODE REVIEW

**Comment by imdevarsh** [comment]
I could make this Tailwind if you want.

**Comment by hello-smile6** [comment]
> I could make this Tailwind if you want.

But is that worth it? Tailwind is for people who don't want to put in effort.

**Comment by imdevarsh** [comment]
It's not "people who don't want to put in effort" it's to make the code neater, allow fast development, and allows you to make a colour scheme.

**Comment by hello-smile6** [comment]
> It's not "people who don't want to put in effort" it's to make the code neater, allow fast development, and allows you to make a colour scheme.

Oh, so what about https://github.com/JaydenDev/searchocean/issues/2#issuecomment-1002358303?

**Comment by jdev082** [comment]
@webdev03 I'd prefer this be done in tailwind yes, go ahead.

**Comment by jdev082** [comment]
@webdev03 go to #2 and you can start. Closing PR.

**Comment by hello-smile6** [comment]
> @webdev03 go to #2 and you can start. Closing PR.

Fine. **Reject another one of my PRs for no reason and I delete every fork I have of things you've made.**

**Pull request closed without merging**
