### PR TITLE
Fix layout

### PR DESCRIPTION
**Pull request by hello-smile6**

### CODE REVIEW

**Comment by jdev082** [comment]
1. &nbsp isn't supposed to have a ; this isn't javascript.
2. Test it first and send me a screenshot.

**Comment by jdev082** [comment]
This PR doesn't even CHANGE anything. LMAO

**Comment by hello-smile6** [comment]
> 1. &nbsp isn't supposed to have a ; this isn't javascript.
> 2. Test it first and send me a screenshot.

Oh, it actually **is** supposed to have it. Sorry you lack the intelligence to know that.

**Comment by imdevarsh** [comment]
> This PR doesn't even CHANGE anything. LMAO

https://github.com/LankyBox01/scratch-trust/pull/1 changed nothing though.

**Pull request closed without merging**
