### PR TITLE
Get font-awesome to work, set up nodejs server for replit deployment

### PR DESCRIPTION
**Pull request by hello-smile6**
F*** you.

### CODE REVIEW

**Comment by hello-smile6** [comment]
Here are some statistics for this server, since I know you worry about bloat.
<table>
<tr>
<th>Size of repository (excluding `.git` directory)</th>
<td>2.33 MB (2,453,504 bytes)1.67 MB (1,759,021 bytes)</td>
</tr>
<tr>
<th>Size of repository "on disk" (don't know what this even means, some kind of nonsense with MSFT)</th>
<td>2.33 MB (2,453,504 bytes)</td>
</tr>
<tr>
<th>Number of files, including `node_modules`</th>
<td>338</td>
</tr>
<tr>
<th>Number of directories, including `node_modules`</th>
<td>73</td>
</tr>
</table>

**Comment by hello-smile6** [comment]
> Here are some statistics for this server, since I know you worry about bloat.
> 
> Size of repository (excluding `.git` directory)	1.67 MB (1,759,021 bytes)
> Size of repository "on disk" (don't know what this even means, some kind of nonsense with MSFT)	2.33 MB (2,453,504 bytes)
> Number of files, including `node_modules`	338
> Number of directories, including `node_modules`	73

I had to edit it because I had an incorrect value. All of those stats are after `npm i`.

**Comment by jdev082** [comment]
None of this is needed, closing PR for reason: Useless.

**Comment by jdev082** [comment]
Font awesome didn't stop working in the first place
This is hosted on gh-pages not replit.

**Comment by hello-smile6** [comment]
> Font awesome didn't stop working in the first place This is hosted on gh-pages not replit.

It was broken for me. Also, I added a server part because it would be helpful.

**Comment by hello-smile6** [comment]
> Font awesome didn't stop working in the first place This is hosted on gh-pages not replit.

Here's a screenshot of it not working. uBlock Origin isn't doing anything, I checked.
jaydendev github io_searchocean_
I used the "Capture node screenshot" button on `document.body`

**Comment by jdev082** [comment]
I don't have my latest commits uploaded, its all since been fixed.

**Comment by hello-smile6** [comment]
> I don't have my latest commits uploaded, its all since been fixed.

Okay

**Comment by jdev082** [comment]
https://jaydendev.github.io/searchocean/
updated.

**Pull request closed without merging**
