### PR TITLE
Add tailwind

### LINKED ISSUE #9: Switch to Tailwind
Switch to a correct Tailwind configuration. This will allow dark mode to be used.

### PR DESCRIPTION
**Pull request by imdevarsh**
Resolves #9

This requires the command `pnpm run tailwind:watch` and dependencies to be installed. It will make the project much faster, though, and I can even make a github action to automatically build the `out.css` file (I've done it before)

PostCSS is what Tailwind uses. Tailwind is actually a PostCSS "plugin". I've added some other ones, like `autoprefixer` (which adds vendor prefixes like `-webkit-` for cross browser support) and `postcss-minify` (minifies the code to make it even more efficient)

### CODE REVIEW

**Comment by imdevarsh** [comment]
yes, finally, my brain can work on this project, intellisense for the win!

**Comment by imdevarsh** [comment]
It's still a static site (no sveltekit) but it adds this. That's why, for people who don't want to use the builder on the computer, I can create the action.

**Comment by imdevarsh** [comment]
This also prevents any breaking changes like if Tailwind 4.0 comes, then we will be prepared.

**Comment by imdevarsh** [comment]
Look, it automatically builds it for us.

**Comment by jdev082** [comment]
Is this REALLY neccesary? I think its just repo bloat.

**Comment by jdev082** [comment]
Also its not an "incorrect" tailwind implementation.

**Comment by jdev082** [comment]
explain what "remove workarounds" means

**Comment by imdevarsh** [comment]
It's not bloat.

**Comment by imdevarsh** [comment]
You added some `&nbsp` thing, when you could have used Tailwind `space-x` instead.

**Comment by jdev082** [comment]
> You added some `&nbsp` thing, when you could have used Tailwind `space-x` instead.

that was left from when I didn't use tailwind.

**Comment by imdevarsh** [comment]
Oh, ok. But still, this is good, and it doesn't affect people who don't want to use this too much (as long as their actions are on).

**Comment by jdev082** [comment]
3 files to many more.
@webdev03 Also this GH-Pages set up is meant to be completely automated.

**Comment by imdevarsh** [comment]
GH Pages is still fully automated.

**Comment by imdevarsh** [comment]
`tailwind.config.js` allows you to change the settings of Tailwind. `postcss.config.js` allows you to add PostCSS plugins if you want them. `pnpm-lock.yaml` and `package.json` are for installing stuff. Also, try to install dependencies, delete `node_modules` and then `pnpm i`. It's insanely fast.

**Pull request merged**
